#! python


#def build(ctx):

    # Illustrate simple use of run_py_script
 #   ctx(
  #      features='run_py_script',
   #     source=['get_simulation_draws.py',
    #    target=ctx.path_to(ctx, 'OUT_DATA', #'initial_locations.csv'),
 #       name='get_simulation_draws'
  #  )

def build(ctx):
    ctx.recurse('data_functions')
    ctx.recurse('CEX_percentiles')
    ctx.recurse('CEX_expenditures')
    ctx.recurse('CPI_management')
    ctx.recurse('Concordance_preparation')    
    ctx.recurse('CPI_concordance_merge')
    ctx.recurse('CEX_CPI_merge')
    ctx.recurse('CEX_CPI_calculations')


