#! python


def build(ctx):
    
    for confile in 'WC', 'BLS':

        # Illustrate simple use of run_py_script
        ctx(
            features='run_py_script',
            source='4_CPI_concordance_merge.py',
            deps=[
                  ctx.path_to(ctx,"OUT_DATA_CON_PREP", "{}_con".format(confile)),
	          ctx.path_to(ctx, "OUT_DATA_CPI_CLEARED", "CPI_for_con")


                 ],
            target=[
               ctx.path_to(ctx,"OUT_DATA_CPI_CON", "CPI_m_{}".format(confile)),
               ],
            append=confile,
            name= ['CPI_m_{}'.format(confile)]
        )
