#! python


def build(ctx):
    

        # Illustrate simple use of run_py_script
        ctx(
            features='run_py_script',
            source='4_CPI_concordance_merge.py',
            deps=[
                  ctx.path_to(ctx,"OUT_DATA_CON_PREP", "WC_con"),
		  ctx.path_to(ctx,"OUT_DATA_CON_PREP", "BLS_con"),
	          ctx.path_to(ctx, "OUT_DATA_CPI_CLEARED", "CPI_for_con")


                 ],
            target=[
              ctx.path_to(ctx,"OUT_DATA_CPI_CON", "CPI_m_WC"),
              ctx.path_to(ctx,"OUT_DATA_CPI_CON", "CPI_m_BLS"),
               ],
            name= 'CPI_m'
        )
