#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features='run_py_script',
        source='3_CPI_DATA_preparation.py',
        deps=[
              ctx.path_to(ctx,'IN_DATA_CPI','food_and_beverages.txt'),
              ctx.path_to(ctx,'IN_DATA_CPI','USApparel.txt'),
              ctx.path_to(ctx,'IN_DATA_CPI','USCommoditiesServicesSpecial.txt'),
              ctx.path_to(ctx,'IN_DATA_CPI','USEducationandCommunication.txt'),
              ctx.path_to(ctx,'IN_DATA_CPI','UShousing.txt'),
              ctx.path_to(ctx,'IN_DATA_CPI','USMedical.txt'),
              ctx.path_to(ctx,'IN_DATA_CPI','USOtherGoodsAndServices.txt'),
              ctx.path_to(ctx,'IN_DATA_CPI','USRecreation.txt'),
              ctx.path_to(ctx,'IN_DATA_CPI','USTransportation.txt'),
              ctx.path_to(ctx,'IN_DATA_CON','ELIconcordance_NS.xls'),

             ],
        target=[
           ctx.path_to(ctx, "OUT_DATA_CPI_CLEARED", "CPI_for_con"),

           ],
        name= ['CPI_for_con']
    )
