#! python


def build(ctx):


        # Illustrate use of run_py_script with automatic model specification.
        ctx(
            features='run_py_script',
            source='8_evolution_time_comparison.py',
            deps=[
                ctx.path_to(ctx, 'IN_DATA_GRAPH', 'agg_cpi_exp_series_p10' ),
            	ctx.path_to(ctx, 'IN_DATA_GRAPH', 'agg_cpi_exp_series_p90' ),
		ctx.path_to(ctx, 'IN_DATA_GRAPH', 'exp_series_p10' ),
		ctx.path_to(ctx, 'IN_DATA_GRAPH', 'exp_series_p90' ),
		],
            target=[
                ctx.path_to(ctx, 'OUT_FIGURES', 'comparison_agg_vs_het_100.png'),
                ctx.path_to(ctx, 'OUT_FIGURES', 'comparison_agg_vs_het_p10.png'),
                ctx.path_to(ctx, 'OUT_FIGURES', 'agg_rich_vs_poor.png'),
                ctx.path_to(ctx, 'OUT_FIGURES', 'het_rich_vs_poor.png'),
            ],
            name='comparison'
        )
