#! python


def build(ctx):


        # Illustrate use of run_py_script with automatic model specification.
        ctx(
            features='run_py_script',
            source='8_evolution_time_comparison.py',
            deps=[
                ctx.path_to(ctx, 'IN_DATA_GRAPH', 'agg_cpi_exp_series_p10' ),
            	ctx.path_to(ctx, 'IN_DATA_GRAPH', 'agg_cpi_exp_series_p90' ),
		ctx.path_to(ctx, 'IN_DATA_GRAPH', 'exp_series_p10' ),
		ctx.path_to(ctx, 'IN_DATA_GRAPH', 'exp_series_p90' ),
		],
            target=[
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'comparison_exp_p1-p10_agg'),
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'comparison_exp_p90-p100_agg'),
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'exp_p1-p10_agg_rich_vs_poor'),
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'exp_p1-p10_rich_vs_poor'),
            ],
            name='comparison'
        )
