#! python


def build(ctx):

    #for s in 'research_paper':
        ctx(
            features='tex',
            source='research_paper.tex',
            prompt=1,
            name='research_paper'
        )
        # Install to the project root.
        ctx.install_files(
            ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
            'research_paper.pdf'
        )
        # Running LaTeX processes in parallel leads to
        # too many potential problems.
        ctx.add_group()
